Description: Html To Pdf Service
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  rootPath:
    Type: String
    Description: The API service's root path
  TestClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of test cluster
    Default: TestClusterName
  ProductionClusterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Name of production cluster
    Default: ProductionClusterName
  environmentSuffix:
    Type: String
    AllowedValues:
      - ''
      - -int
      - -sys
    Description: Environment suffix e.g -int -sys

Conditions:
  isTesting: !Or
    - !Equals [!Ref environmentSuffix, "-int"]
    - !Equals [!Ref environmentSuffix, "-sys"]

Resources:
  htmlToPdfRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: [ "ecs-tasks.amazonaws.com" ]
            Action: [ "sts:AssumeRole" ]
      Path: "/"
      Policies:
      - PolicyName: htmlToPdfServices
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:SendMessage
            Resource:
              Fn::ImportValue: logging-queue-arn
  htmlToPdfTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !GetAtt htmlToPdfRole.Arn
      ContainerDefinitions:
      - Name: gotenberg
        Cpu: '1'
        Essential: 'true'
        Image: !Sub gotenberg/gotenberg:8.4.0
        PortMappings:
        - ContainerPort: 3000
        Memory: '512'
        HealthCheck:
          Command:
            - "CMD-SHELL"
            - "curl -f http://localhost:3000/health || exit 1"
        DockerLabels:
          traefik.enable: true
          traefik.http.routers.pdf-service.entrypoints: web
          traefik.http.routers.pdf-service.rule: "PathPrefix(`/pdf-service`)"
          traefik.http.services.pdf-service.loadbalancer.healthcheck.path: "/health"
        LogConfiguration:
          LogDriver: gelf
          Options:
            'gelf-address': 'udp://syslog.linn.co.uk:12201'
            'tag': !Sub gotenberg-8-ecs-task
        Environment:
        - Name: awsRegion
          Value: !Ref AWS::Region
        - Name: 'ROOT_PATH'
          Value: !Ref rootPath  
        
  htmlToPdfService:
    Type: AWS::ECS::Service
    Properties:
      # Have to use long form conditional
      Cluster: !If
        - isTesting
        - !Sub ${TestClusterName}
        - !Sub ${ProductionClusterName}
      DesiredCount: !If [ isTesting, 1, 2]
      PlacementStrategies:
        - Field: attribute:ecs.availability-zone
          Type: spread
        - Field: instanceId
          Type: spread
      TaskDefinition: !Ref htmlToPdfTaskDefinition
      Role: ecsServiceRole